apps/jobs/urls.py
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^$', views.welcome, name='welcome'),
    re_path(r'^logout/$', views.logout, name='logout'),
    re_path(r'^jobs/new/$', views.new_job, name='new_job'),
    re_path(r'^dashboard/$', views.dashboard, name='dashboard'),
    re_path(r'^jobs/(?P<id>\d+)/$', views.view_job, name='view_job'),
    re_path(r'^jobs/edit/(?P<id>\d+)/$', views.edit_job, name='edit_job'),
    re_path(r'^dashboard/jobs/remove/$', views.remove_job, name='remove_job'),
    re_path(r'^dashboard/jobs/giveup/$', views.giveup_job, name='giveup_job'),
    re_path(r'^process/signup/$', views.process_signup, name='process_signup'),
    re_path(r'^process/signin/$', views.process_signin, name='process_signin'),
    re_path(r'^jobs/user/add/(?P<id>\d+)/$', views.add_user_job, name='add_user_job'),
    re_path(r'^jobs/giveup/(?P<id>\d+)/$', views.giveup_the_job, name='giveup_the_job'),
    re_path(r'^dashboard/user/jobs/add/$', views.add_job_to_user, name='add_job_to_user'),
    re_path(r'^dashboard/jobs/new/process/$', views.process_new_job, name='process_new_job'),
    re_path(r'^process/jobs/edit/(?P<id>\d+)/$', views.process_job_edit, name='process_job_edit'),
]

handy_helper/urls.py
from django.urls import re_path, include
from django.conf.urls import handler400, handler403, handler404, handler500
from django.contrib import admin

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include('apps.jobs.urls', namespace='jobs'))
]

handler404 = 'jobs.views.error_404'
handler500 = 'jobs.views.error_500'
handler403 = 'jobs.views.error_403'
handler400 = 'jobs.views.error_400'

apps/jobs/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.contrib import messages
from .models import User, Job
from django.views.decorators.csrf import csrf_protect, csrf_exempt
from django.core.urlresolvers import reverse
import bcrypt

def welcome(request):
    if 'user_id' in request.session:
        return redirect(reverse('jobs:dashboard'))
    return render(request, 'jobs/welcome.html')

def process_signup(request):
    if request.method == 'POST':
        errors =  User.objects.registration_validations(request.POST)
        if len(errors):
            for k, v in errors.items():
                messages.error(request, v, extra_tags=k)
            return redirect(reverse('jobs:welcome'))
        else:
            user_password_hash = bcrypt.hashpw(request.POST['password'].encode(), bcrypt.gensalt())
            user = User(first_name=request.POST['first_name'], last_name=request.POST['last_name'], 
                email=request.POST['email'], password_hash=user_password_hash
            )
            user.save()
            messages.success(request, f'Successful registration', extra_tags='registration_success')
            request.session['user_id'] = str(user.id)
            return redirect(reverse('jobs:dashboard'))
    return redirect(reverse('jobs:welcome'))

def process_signin(request):
    if request.method == 'POST':
        errors =  User.objects.signin_validations(request.POST)
        if len(errors):
            for k, v in errors.items():
                messages.error(request, v, extra_tags=k)
            return redirect(reverse('jobs:welcome'))
        else:
            user = User.objects.filter(email=request.POST['signin_email'])[0]
            request.session['user_id'] = str(user.id)
            messages.success(request, f'Successful login', extra_tags='login_success')
            return redirect(reverse('jobs:dashboard'))
    return redirect(reverse('jobs:welcome'))

def dashboard(request):
    if 'user_id' in request.session:
        user = User.objects.filter(id=request.session['user_id'])
        if len(user) > 0: 
            user = user[0]
            user_jobs = Job.objects.filter(added_by=user)
            everyone_jobs = Job.objects.filter(added_by=None)
            context = {
                'user': user,
                'everyone_jobs': everyone_jobs,
                'user_jobs': user_jobs
            }
            return render(request, 'jobs/dashboard.html', context)
    return redirect(reverse('jobs:welcome'))

def new_job(request):
    if 'user_id' in request.session:
        user = User.objects.filter(id=request.session['user_id'])
        if len(user) > 0: 
            user = user[0]
            context = {
                'user': user
            }
            return render(request, 'jobs/new_job.html', context)
    return redirect(reverse('jobs:welcome'))

def process_new_job(request):
    if 'user_id' in request.session:
        if request.method == 'POST':
            errors =  Job.objects.job_validations(request.POST)
            if len(errors):
                for k, v in errors.items():
                    messages.error(request, v, extra_tags=k)
                return redirect(reverse('jobs:new_job'))
            else:
                category = request.POST['category']
                if len(request.POST['other_category']) > 0: 
                    category = request.POST['other_category']
                created_by = User.objects.filter(id=request.session['user_id'])[0]
                job = Job(created_by=created_by, title=request.POST['title'], category=category,
                    description=request.POST['description'], location=request.POST['location']
                )
                job.save()
                messages.success(request, f'Successful job creation', extra_tags='new_job_success')
                return redirect(reverse('jobs:dashboard'))
    return redirect(reverse('jobs:welcome'))

@csrf_exempt
def add_job_to_user(request):
    if 'user_id' in request.session:
        if request.method == 'POST':
            user = User.objects.filter(id=request.session['user_id'])
            if len(user) > 0: 
                user = user[0]
                for k, v in request.POST.items():
                    job = Job.objects.filter(id=v)[0]
                    job.added_by = user
                    job.save()
                everyone_jobs = Job.objects.filter(added_by=None)
                user_jobs = Job.objects.filter(added_by__id=request.session['user_id'])
                context = {
                    'user': user,
                    'everyone_jobs': everyone_jobs,
                    'user_jobs': user_jobs
                }
                return render(request, 'jobs/job_tables.html', context)
    return redirect(reverse('jobs:welcome'))

def logout(request):
    if 'user_id' in request.session:
        del request.session['user_id']
    return redirect(reverse('jobs:welcome'))

@csrf_exempt
def remove_job(request):
    if 'user_id' in request.session:
        user = User.objects.filter(id=request.session['user_id'])
        if len(user) > 0: 
            user = user[0]
            for k, v in request.POST.items():
                Job.objects.filter(id=v)[0].delete()
            everyone_jobs = Job.objects.filter(added_by=None)
            user_jobs = Job.objects.filter(added_by__id=request.session['user_id'])
            context = {
                'user': user,
                'everyone_jobs': everyone_jobs,
                'user_jobs': user_jobs
            }
            return render(request, 'jobs/job_tables.html', context)
    return redirect(reverse('jobs:welcome'))

def edit_job(request, id):
    if 'user_id' in request.session:
        user = User.objects.filter(id=request.session['user_id'])
        if len(user) > 0: 
            user = user[0]
            job = Job.objects.filter(id=id)
            if len(job) > 0: 
                job = job[0]
                if job.created_by == user:
                    context = {
                        'user': user,
                        'job': job
                    }
                    return render(request, 'jobs/edit_job.html', context)
            return redirect(reverse('jobs:dashboard'))
    return redirect(reverse('jobs:welcome'))

def process_job_edit(request, id):
    if 'user_id' in request.session:
        if request.method == 'POST':
            errors =  Job.objects.job_validations(request.POST)
            if len(errors):
                for k, v in errors.items():
                    messages.error(request, v, extra_tags=k)
                return redirect(reverse('jobs:edit_job', kwargs={'id':id}))
            else:
                job = Job.objects.filter(id=id)
                if len(job) > 0: 
                    job = job[0]
                    job.title = request.POST['title']
                    job.description = request.POST['description']
                    job.location = request.POST['location']
                    job.save()
                    messages.success(request, f'Successful job edit', extra_tags='edit_job_success')
                    return redirect(reverse('jobs:dashboard'))
    return redirect(reverse('jobs:welcome'))

def view_job(request, id):
    if 'user_id' in request.session:
        user = User.objects.filter(id=request.session['user_id'])
        if len(user) > 0: 
            user = user[0]
            job = Job.objects.filter(id=id)
            if len(job) > 0: 
                job = job[0]
                context = {
                    'user': user,
                    'job': job
                }
                return render(request, 'jobs/view_job.html', context)
            return redirect(reverse('jobs:dashboard'))
    return redirect(reverse('jobs:welcome'))

def add_user_job(request, id):
    if 'user_id' in request.session:
        user = User.objects.filter(id=request.session['user_id'])
        if len(user) > 0: 
            user = user[0]
            job = Job.objects.filter(id=id)
            if len(job) > 0: 
                job = job[0]
                if job.added_by == None:
                    job.added_by = user
                    job.save()
                    return redirect(reverse('jobs:view_job', kwargs={'id':id}))
    return redirect(reverse('jobs:welcome'))

@csrf_exempt
def giveup_job(request):
    if 'user_id' in request.session:
        user = User.objects.filter(id=request.session['user_id'])
        if len(user) > 0: 
            user = user[0]
            for k, v in request.POST.items():
                job = Job.objects.filter(id=v)[0]
                job.added_by = None
                job.save()
            everyone_jobs = Job.objects.filter(added_by=None)
            user_jobs = Job.objects.filter(added_by__id=request.session['user_id'])
            context = {
                'user': user,
                'everyone_jobs': everyone_jobs,
                'user_jobs': user_jobs
            }
            return render(request, 'jobs/job_tables.html', context)
    return redirect(reverse('jobs:welcome'))

def giveup_the_job(request, id):
    if 'user_id' in request.session:
        user = User.objects.filter(id=request.session['user_id'])
        if len(user) > 0: 
            user = user[0]
            job = Job.objects.filter(id=id)
            if len(job) > 0: 
                job = job[0]
                job.added_by = None
                job.save()
                return redirect(reverse('jobs:view_job', kwargs={'id':id}))
    return redirect(reverse('jobs:welcome'))

def error_404(request):
        data = {}
        return render(request,'jobs/404.html', data)

def error_500(request):
        data = {}
        return render(request,'jobs/500.html', data)

apps/jobs/templates/jobs/edit_job.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Edit Job</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="Mmedara Josiah">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&display=swap">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/8.4.6/js/utils.js"></script>
        {% load static %}
        <link rel="stylesheet" href="{% static 'jobs/css/bootstrap/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'jobs/css/edit_job.css' %}">
        <script src="{% static 'jobs/js/bootstrap/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'jobs/js/edit_job.js' %}"></script>
    </head>
    <body>
        <div class="position-relative container-fluid">
            {% if user %}
                {% if job %}
                    <div class="row">
                        <div class="mb-8 py-8 pt-7 px-10">
                            <div class="d-flex justify-content-between align-items-center pt-4">
                                <div class="">
                                    <h3>Hello {{user.first_name}}! Let's edit your job!</h3>
                                </div>
                                <div class="d-flex justify-content-end align-items-end">
                                    <a class="link-primary fw-bold" id="logout" style="color: blue;" href="{% url 'jobs:logout' %}" data-toggle="modal" data-target="#logoutModal">Logout</a>
                                    <div class="modal fade" id="logoutModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">Logout</h5>
                                                    <button type="button" class="close" id="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <p>Are you sure you want to logout?</p>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" id="no" data-dismiss="modal">No</button>
                                                    <a class="btn btn-danger" href="#" id="yes">Yes</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="border border-dark py-8 px-10">
                                <form action="{% url 'jobs:process_job_edit' id=job.id %}" method="post" id="edit_job_form">
                                    {% csrf_token %}
                                    <div class="row py-lg-16">
                                        <div class="form-group d-flex justify-content-center align-items-center mb-6">
                                            <div class="" style="width: 110px; height: 50px;">
                                                <label class="me-4 align-top" for="title">Title:</label>
                                            </div>
                                            <div class="" style="height: 80px; width: 300px;">
                                                <input class="form-control border border-dark" type="text" name="title" id="title" value="{{job.title}}">
                                                {%if messages%}
                                                    {%for message in messages%}
                                                        {% if 'title' in message.extra_tags %}
                                                            <small style="color: red;" class="{{message.tags}}">{{message}}</small>
                                                        {% endif %}
                                                    {%endfor%}
                                                {%endif%}
                                            </div>
                                        </div>
                                        <div class="form-group d-flex justify-content-center align-items-center mb-6">
                                            <div class="" style="width: 110px; height: 50px;">
                                                <label class="me-4" for="description">Description:</label>
                                            </div>
                                            <div class="" style="height: 80px; width: 300px;">
                                                <input class="form-control border border-dark" type="text" name="description" id="description" value="{{job.description}}">
                                                {%if messages%}
                                                    {%for message in messages%}
                                                        {% if 'description' in message.extra_tags %}
                                                            <small style="color: red;" class="{{message.tags}}">{{message}}</small>
                                                        {% endif %}
                                                    {%endfor%}
                                                {%endif%}
                                            </div>
                                        </div>
                                        <div class="form-group d-flex justify-content-center align-items-center mb-6">
                                            <div class="" style="width: 110px; height: 50px;">
                                                <label class="me-4" for="location">Location:</label>
                                            </div>
                                            <div class="" style="height: 80px; width: 300px;">
                                                <input class="form-control border border-dark" type="text" name="location" id="location" value="{{job.location}}">
                                                {%if messages%}
                                                    {%for message in messages%}
                                                        {% if 'location' in message.extra_tags %}
                                                            <small style="color: red;" class="{{message.tags}}">{{message}}</small>
                                                        {% endif %}
                                                    {%endfor%}
                                                {%endif%}
                                            </div>
                                        </div>
                                        <div class="form-group d-flex justify-content-center align-items-center mb-6">
                                            <a class="btn btn-secondary me-4" href="{% url 'jobs:dashboard' %}">Cancel</a>
                                            <input class="btn btn-success" type="submit" name="submit" id="submit" value="Submit">
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endif %}
        </div>
    </body>
</html>

apps/jobs/templates/jobs/job_tables.html
{% load static %}
<script src="{% static 'jobs/js/job_tables.js' %}"></script>
<div class="row mb-8">
    {% if everyone_jobs %}
        <p>Everyone's jobs:</p>
        {% if everyone_jobs|length > 0 %}
            <table class="table table-stripped">
                <thead>
                    <tr>
                        <th scope="col">Job</th>
                        <th scope="col">Location</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for job in everyone_jobs %}
                        <tr>
                            <td>{{job.title}}</td>
                            <td>{{job.location}}</td>
                            <td>
                                <a style="color: blue;" href="{% url 'jobs:view_job' id=job.id %}">View</a> &nbsp;|&nbsp;
                                {% if job.created_by == user %}
                                    <a style="color: blue;" href="#" data-toggle="modal" data-target="#removeModal{{job.id}}" class="remove">Remove</a> &nbsp;|&nbsp;
                                    <div class="modal removeModal" id="removeModal{{job.id}}" tabindex="-1" aria-labelledby="exampleModalLabel{{job.id}}" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel{{job.id}}">Remove Job</h5>
                                                    <button type="button" class="remove_close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <p>Are you sure you want to remove the {{job.title}} job?</p>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary remove_no" data-dismiss="modal">No</button>
                                                    <a class="btn btn-danger remove_yes" href="#" data-id="{{job.id}}" >Yes</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <a style="color: blue;" href="{% url 'jobs:edit_job' id=job.id %}">Edit</a> &nbsp;|&nbsp;
                                {% endif %}
                                <a style="color: blue;" class="add" href="#" id="add" data-job="{{job.id}}">Add</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% endif %}
    {% else %}
        <p>There are no jobs right now</p>
    {% endif %}
</div>
<div class="row mb-8">
    {% if user_jobs %}
        <p>{{user.first_name}}'s jobs:</p>
        {% if user_jobs|length > 0 %}
            <table class="table table-stripped">
                <thead>
                    <tr>
                        <th scope="col">Job</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for job in user_jobs %}
                        <tr>
                            <td>{{job.title}}</td>
                            <td>
                                <a style="color: blue;" href="{% url 'jobs:view_job' id=job.id %}">View</a> &nbsp;|&nbsp;
                                <a style="color: blue;" href="#" class="done" id="done" data-job="{{job.id}}">Done</a> &nbsp;|&nbsp;
                                <a style="color: blue;" href="#" class="give_up" data-job="{{job.id}}">Give up</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% endif %}
    {% else %}
        <p>{{user.first_name}} has no jobs right now</p>
    {% endif %}
</div>

apps/jobs/templates/jobs/view_job.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>New Job</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="Mmedara Josiah">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&display=swap">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/8.4.6/js/utils.js"></script>
        {% load static %}
        <link rel="stylesheet" href="{% static 'jobs/css/bootstrap/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'jobs/css/view_job.css' %}">
        <script src="{% static 'jobs/js/bootstrap/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'jobs/js/view_job.js' %}"></script>
    </head>
    <body>
        <div class="position-relative container-fluid">
            {% if user %}
                {% if job %}
                    <div class="row">
                        <div class="mb-8 py-8 pt-7 px-10">
                            <div class="d-flex justify-content-between align-items-center pt-4 mb-6">
                                <div class="me-4">
                                    <h3>Hello {{user.first_name}}! These are the job details!</h3>
                                </div>
                                <div class="d-flex justify-content-end align-items-end">
                                    <a class="link-primary fw-bold me-4" style="color: blue;" href="{% url 'jobs:dashboard' %}">Dashboard</a>
                                    <a class="link-primary fw-bold" id="logout" style="color: blue;" href="{% url 'jobs:logout' %}" data-toggle="modal" data-target="#logoutModal">Logout</a>
                                    <div class="modal fade" id="logoutModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">Logout</h5>
                                                    <button type="button" class="close" id="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <p>Are you sure you want to logout?</p>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" id="no" data-dismiss="modal">No</button>
                                                    <a class="btn btn-danger" href="#" id="yes">Yes</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <p class="fw-bold">{{job.title}}</p>
                            <div class="border border-dark py-8 px-10 mb-6">
                                <p>{{job.description}}</p>
                                <p>Location: {{job.location}}</p>
                                <p>Posted by: {{job.created_by.first_name}} {{job.created_by.last_name}}</p>
                                <p>Posted on: {{job.created_at}}</p>
                                <p>Categories: {{job.category}}</p>
                            </div>
                            {% if job.added_by != user %}
                                <a class="link-primary fw-bold" style="color: blue;" href="{% url 'jobs:add_user_job' id=job.id %}">Add to my jobs</a>
                            {% else %}
                                <a style="color: blue;" href="{% url 'jobs:giveup_the_job' id=job.id %}" class="give_up link-primary fw-bold">Give up</a>
                            {% endif %}
                        </div>
                    </div>
                {% endif %}
            {% endif %}
        </div>
    </body>
</html>